=== Aptivi/NitrocidKS/public/Nitrocid/Resources/Schemas/SettingsSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Settings Schema",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "Name": {
                "type": "string"
            },
            "Desc": {
                "type": "string"
            },
            "DisplayAs": {
                "type": "string"
            },
            "Keys": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "Name": {
                            "type": "string"
                        },
                        "Type": {
                            "type": "string"
                        },
                        "Variable": {
                            "type": "string"
                        },
                        "Description": {
                            "type": "string"
                        },
                        "Masked": {
                            "type": "boolean"
                        },
                        "IsEnumeration": {
                            "type": "boolean"
                        },
                        "SelectionFunctionName": {
                            "type": "string"
                        },
                        "SelectionFunctionType": {
                            "type": "string"
                        },
                        "IsSelectionFunctionDict": {
                            "type": "boolean"
                        },
                        "SelectionFunctionArgs": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "ArgType": {
                                        "type": "string"
                                    },
                                    "ArgValue": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "SelectionFallback": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "EnumerationInternal": {
                            "type": "boolean"
                        },
                        "Enumeration": {
                            "type": "string"
                        },
                        "EnumerationAssembly": {
                            "type": "string"
                        },
                        "EnumerationZeroBased": {
                            "type": "boolean"
                        },
                        "UnsupportedPlatforms": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "IsValuePath": {
                            "type": "boolean"
                        },
                        "IsPathCurrentPath": {
                            "type": "boolean"
                        },
                        "DelimiterVariable": {
                            "type": "string"
                        },
                        "DelimiterVariableType": {
                            "type": "string"
                        },
                        "ShellType": {
                            "type": "string"
                        },
                        "MinimumValue": {
                            "type": "number"
                        },
                        "MaximumValue": {
                            "type": "number"
                        },
                        "Delimiter": {
                            "type": "string"
                        },
                        "ValuePathType": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "Name",
                        "Type"
                    ]
                }
            }
        },
        "required": [
            "Name",
            "Desc",
            "Keys"
        ]
    }
}

=== Aptivi/NitrocidKS/public/Nitrocid/Resources/Settings/SettingsEntries.json
[
    {
        "Name": "General",
        "Desc": "This section lists all general kernel settings, mainly for maintaining the kernel.",
        "DisplayAs": "General kernel settings",
        "Keys": [
            {
                "Name": "Check for Updates on Startup",
                "Type": "SBoolean",
                "Variable": "CheckUpdateStart",
                "Description": "Each startup, it will check for updates."
            },
            {
                "Name": "Custom Startup Banner",
                "Type": "SString",
                "Variable": "CustomBanner",
                "Description": "If specified, it will display customized startup banner with placeholder support. You can use {0} for kernel version."
            },
            {
                "Name": "Change Culture when Switching Languages",
                "Type": "SBoolean",
                "Variable": "LangChangeCulture",
                "Description": "When switching languages, change the month names, calendar, etc."
            },
            {
                "Name": "Language",
                "Type": "SSelection",
                "Variable": "CurrentLanguage",
                "IsEnumeration": false,
                "SelectionFunctionName": "ListAllLanguagesWithCountry",
                "SelectionFunctionType": "LanguageManager",
                "IsSelectionFunctionDict": true,
                "SelectionFallback": [ "en-US" ],
                "Description": "Specifies the kernel language."
            },
            {
                "Name": "Culture",
                "Type": "SSelection",
                "Variable": "CurrentCultStr",
                "IsEnumeration": false,
                "SelectionFunctionName": "GetCultureNamesFromCurrentLang",
                "SelectionFunctionType": "CultureManager",
                "SelectionFallback": [ "en-US" ],
                "Description": "Which variant of the current language is being used to change the month names, calendar, etc.?"
            },
            {
                "Name": "Show app information during boot",
                "Type": "SBoolean",
                "Variable": "ShowAppInfoOnBoot",
                "Description": "Shows brief information about the application on boot."
            },
            {
                "Name": "Show stage finish times",
                "Type": "SBoolean",
                "Variable": "ShowStageFinishTimes",
                "Description": "Shows how much time did the kernel take to finish a stage."
            },
            {
                "Name": "Start kernel modifications on boot",
                "Type": "SBoolean",
                "Variable": "StartKernelMods",
                "Description": "Automatically start the kernel modifications on boot."
            },
            {
                "Name": "Show current time before login",
                "Type": "SBoolean",
                "Variable": "ShowCurrentTimeBeforeLogin",
                "Description": "Shows the current time, time zone, and date before logging in."
            },
            {
                "Name": "Notify for any fault during boot",
                "Type": "SBoolean",
                "Variable": "NotifyFaultsBoot",
                "Description": "If there is a minor fault during kernel boot, notifies the user about it."
            },
            {
                "Name": "Show stack trace on kernel error",
                "Type": "SBoolean",
                "Variable": "ShowStackTraceOnKernelError",
                "Description": "If there is any kernel error, choose whether or not to print the stack trace to the console."
            },
            {
                "Name": "Enable event debugging",
                "Type": "SBoolean",
                "Variable": "EventDebug",
                "Description": "Enables debugging for the kernel event system"
            },
            {
                "Name": "Stylish splash screen",
                "Type": "SBoolean",
                "Variable": "EnableSplash",
                "Description": "Enables the stylish splash screen on startup. Please note that it will disable argument prompt and test shell pre-boot."
            },
            {
                "Name": "Splash name",
                "Type": "SSelection",
                "Variable": "SplashName",
                "IsEnumeration": false,
                "SelectionFunctionName": "GetNamesOfSplashes",
                "SelectionFunctionType": "SplashManager",
                "SelectionFallback": [ "Simple" ],
                "Description": "Splash name from the available splashes implemented in the kernel."
            },
            {
                "Name": "Simulate No APM Mode",
                "Type": "SBoolean",
                "Variable": "SimulateNoAPM",
                "Description": "Whether to simulate a situation where there is no APM available. If enabled, it informs the user that it's now safe to turn off the computer upon shutdown."
            },
            {
                "Name": "Beep on shutdown or reboot",
                "Type": "SBoolean",
                "Variable": "BeepOnShutdown",
                "Description": "Enables beeping upon shutting down the kernel."
            },
            {
                "Name": "Delay on shutdown or reboot",
                "Type": "SBoolean",
                "Variable": "DelayOnShutdown",
                "Description": "Enables delaying upon shutting down the kernel."
            },
            {
                "Name": "Console supports true color",
                "Type": "SBoolean",
                "Variable": "ConsoleSupportsTrueColor",
                "Description": "If you are sure that the console supports true color, or if you want to change your terminal to a terminal that supports true color, change this value."
            },
            {
                "Name": "Set codepage",
                "Type": "SBoolean",
                "Variable": "SetCodepage",
                "Description": "Set the language codepage upon switching languages.",
                "UnsupportedPlatforms": [ "Unix", "macOS" ]
            },
            {
                "Name": "Development notice acknowledged",
                "Type": "SBoolean",
                "Variable": "DevNoticeConsented",
                "Description": "If set to true, the kernel won't show you the development notice every time you boot to the kernel in development versions."
            },
            {
                "Name": "Allow loading untrusted mods",
                "Type": "SBoolean",
                "Variable": "AllowUntrustedMods",
                "Description": "If set to true, the kernel won't error out upon loading mods that don't have the signed public key."
            },
            {
                "Name": "Use system time zone",
                "Type": "SBoolean",
                "Variable": "UseSystemTimeZone",
                "Description": "If this option is enabled, the kernel uses the time zone from your computer settings. Else, uses the kernel-wide time zone that can be configured."
            },
            {
                "Name": "Kernel-wide time zone",
                "Type": "SSelection",
                "Variable": "KernelWideTimeZone",
                "IsEnumeration": false,
                "SelectionFunctionName": "GetTimeZoneNames",
                "SelectionFunctionType": "TimeZones",
                "SelectionFallback": [ "Etc/UTC", "GMT" ],
                "Description": "The kernel-wide time zone to use"
            },
            {
                "Name": "Show the license information box",
                "Type": "SBoolean",
                "Variable": "ShowLicenseInfoBox",
                "Description": "Whether to show the modal license information box for three seconds after each login. It's recommended to keep it on."
            },
            {
                "Name": "Bootloader style",
                "Type": "SString",
                "Variable": "BootStyle",
                "Description": "Select a bootloader style to match your preference."
            },
            {
                "Name": "Bootloader default selection timeout",
                "Type": "SIntSlider",
                "Variable": "BootSelectTimeoutSeconds",
                "Description": "Timeout in seconds to boot to the default selection.",
                "MinimumValue": 0,
                "MaximumValue": 600
            },
            {
                "Name": "Bootloader default selection",
                "Type": "SInt",
                "Variable": "BootSelect",
                "Description": "Default boot entry selection. This number is zero-based, so the first element is index 0, and so on."
            },
            {
                "Name": "Enable 'The Nitrocid Homepage'",
                "Type": "SBoolean",
                "Variable": "EnableHomepage",
                "Description": "Enables 'The Nitrocid Homepage' that allows you to see what's happening in a glance."
            }
        ]
    },
    {
        "Name": "Colors",
        "Desc": "This section lets you choose what type of color do you want to change.",
        "DisplayAs": "Color settings",
        "Keys": [
            {
                "Name": "Use accent colors",
                "Type": "SBoolean",
                "Variable": "UseAccentColors",
                "Description": "If set to true, the theme manager populates accent colors for specific color types that the theme supports."
            },
            {
                "Name": "Foreground accent color",
                "Type": "SColor",
                "Variable": "AccentForegroundColor",
                "Description": "For themes that support accents, this is the accented foregound color."
            },
            {
                "Name": "Background accent color",
                "Type": "SColor",
                "Variable": "AccentBackgroundColor",
